import { useState, useEffect } from "react";

export default function ResourcesDisplay() {
  const [resourcesText, setResourcesText] = useState("");

  useEffect(() => {
    fetch("/resources.txt")
      .then((response) => {
        if (!response.ok) {
          throw new Error("Failed to fetch resources file");
        }
        return response.text();
      })
      .then((data) => setResourcesText(data))
      .catch((error) => console.error("Error loading the file:", error));
  }, []);

  const renderResources = () => {
    if (!resourcesText) return null;

    const lines = resourcesText.split('\n');
    return lines.map((line, index) => {
      if (line.includes("http")) {
        return (
          <a href={line} key={index} target="_blank" rel="noopener noreferrer">
            {line}
          </a>
        );
      } else {
        return <p key={index}>{line}</p>;
      }
    });
  };

  return (
    <div className="resources-container">
      <h2>Helpful Resources Generated by Perplexity</h2>
      {renderResources()}
    </div>
  );
}
